apiVersion: v1
kind: ConfigMap
metadata:
  name: clinical-service-config
  namespace: default
  labels:
    app: clinical-service
data:
  NODE_ENV: "production"
  DB_HOST: "clinical-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "clinical_db"
  USE_MIGRATIONS: "false"

