apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  # MySQL
  - mysql-pvc.yaml
  - mysql-configmap.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - mysql-deployment.yaml
  
  # Clinical Service
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: clinical-service
  app.kubernetes.io/part-of: geno-sentinel

