apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clinical-mysql-pvc
  namespace: default
  labels:
    app: clinical-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # Descomenta y ajusta seg√∫n tu cluster

