apiVersion: v1
kind: Secret
metadata:
  name: clinical-mysql-secret
  namespace: default
  labels:
    app: clinical-mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_PASSWORD: "clinical_password"