apiVersion: v1
kind: Secret
metadata:
  name: clinical-service-secret
  namespace: default
  labels:
    app: clinical-service
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "rootpassword"