apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/part-of: geno-sentinel

