apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
  labels:
    app: api-gateway
type: Opaque
stringData:
  JWT_SECRET: "your-256-bit-secret-key-change-in-production-minimum-32-characters-long-secret-key"

