apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - mongodb-pvc.yaml

commonLabels:
  project: geno-sentinel
  service: genomic
