apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  # MongoDB
  - mongodb-pvc.yaml
  - mongodb-configmap.yaml
  - mongodb-secret.yaml
  - mongodb-service.yaml
  - mongodb-deployment.yaml
  
  # Genomic Service
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: genomic-service
  app.kubernetes.io/part-of: geno-sentinel

