apiVersion: v1
kind: Secret
metadata:
  name: genomic-mongodb-secret
  namespace: default
  labels:
    app: genomic-mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "mongodbpassword"

