apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genomic-mongodb-pvc
  namespace: default
  labels:
    app: genomic-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

