apiVersion: v1
kind: Secret
metadata:
  name: genomic-service-secret
  namespace: default
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXNlY3JldC1rZXktcGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9u
