apiVersion: v1
kind: Secret
metadata:
  name: genomic-service-secret
  namespace: default
  labels:
    app: genomic-service
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-genomic-service-change-in-production"

